language: java

sudo: false

jobs:
    include:
#      - stage: build
#        script: ant build
      - stage: test
        script:
          - ant build
          - _SILENT_JAVA_OPTS="$_JAVA_OPTIONS"
          - unset _JAVA_OPTIONS
          - alias java='java "$_SILENT_JAVA_OPTS"'
          - PROJ="./" busted tests
        env:
          - LUA=lua5.1
          - LUAROCKS=2.3.0
        before_install:
          - source .travis/setenv_lua.sh
          - luarocks install busted
          - luarocks install moonscript
          - luarocks install luafilesystem

