language: java

sudo: false

jobs:
    include:
      - stage: build
        script: ant build
      - stage: test
        script:
          - ant build
          - PROJ="./" busted tests
        env:
          - LUA=lua5.1
          - LUAROCKS=2.3.0
        before_install:
          - source .travis/setenv_lua.sh
          - luarocks install busted
          - luarocks install moonscript
          - luarocks install luafilesystem

