language: java

sudo: false

env:
  - PROJ="./"

jobs:
    include:
      - stage: build
        script: ant build
      - stage: test
        script: busted tests
        env:
          - LUA=lua5.1
        before_install:
          - source .travis/setenv_lua.sh
          - luarocks install busted

